github.com:
    users:
        gusvsconcelos:
            oauth_token: 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
    git_protocol: https
    user: gusvsconcelos
    oauth_token: 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
