[Dynamic]
; White on black background
text               = ${xrdb:foreground}
subtext            = ${xrdb:foreground}
nav-active-text    = 000000
main               = ${xrdb:background}
sidebar            = ${xrdb:background}
player             = ${xrdb:background}
card               = ${xrdb:background}
shadow             = ${xrdb:background}
main-secondary     = 292929
button             = ${xrdb:color9}
button-secondary   = DEDEDE
button-active      = ${xrdb:color14}
button-disabled    = ${xrdb:color8}
nav-active         = DEDEDE
play-button        = DEDEDE
tab-active         = ${xrdb:color9}
notification       = ${xrdb:color0}
notification-error = ${xrdb:color9}
playback-bar       = DEDEDE
misc               = ${xrdb:color0}
selected-row       = ${xrdb:color14}