[Dynamic]
; White on black background
text               = ${xrdb:foreground}
subtext            = ${xrdb:foreground}
nav-active-text    = 000000
main               = ${xrdb:background}
sidebar            = ${xrdb:background}
player             = ${xrdb:background}
card               = ${xrdb:background}
shadow             = ${xrdb:background}
main-secondary     = 292929
button             = ${xrdb:color9}
button-secondary   = ${xrdb:color14}
button-active      = ${xrdb:color9}
button-disabled    = ${xrdb:color8}
nav-active         = ${xrdb:color9}
play-button        = ${xrdb:color14}
tab-active         = ${xrdb:color9}
notification       = ${xrdb:color0}
notification-error = ${xrdb:color14}
playback-bar       = ${xrdb:color14}
misc               = ${xrdb:color0}
selected-row       = ${xrdb:color14}