timeout: 3
default_entry: 3
interface_branding:

term_palette: 15161e;f7768e;9ece6a;e0af68;7aa2f7;bb9af7;7dcfff;a9b1d6
term_palette_bright: 414868;f7768e;9ece6a;e0af68;7aa2f7;bb9af7;7dcfff;c0caf5
term_background: 1a1b26
term_foreground: c0caf5
term_background_bright: 414868
term_foreground_bright: c0caf5

/Arch Linux
    protocol: linux
    path: boot():/vmlinuz-linux-zen
    cmdline: root=PARTUUID=08511545-f996-45c0-b58a-b9b49054e7c9 zswap.enabled=0 rw rootfstype=btrfs quiet splash loglevel=3 rd.systemd.show_status=false rd.udev.log_level=3 udev.log_priority=3
    module_path: boot():/initramfs-linux-zen.img

/Arch Linux (Fallback)
    protocol: linux
    path: boot():/vmlinuz-linux-zen
    cmdline: root=PARTUUID=08511545-f996-45c0-b58a-b9b49054e7c9 zswap.enabled=0 rw rootfstype=btrfs
    module_path: boot():/initramfs-linux-zen-fallback.img

/Arch Linux (CachyOS)
    protocol: linux
    path: boot():/vmlinuz-linux-cachyos
    cmdline: root=PARTUUID=08511545-f996-45c0-b58a-b9b49054e7c9 zswap.enabled=0 rw rootfstype=btrfs quiet splash loglevel=3 rd.systemd.show_status=false rd.udev.log_level=3 udev.log_priority=3
    module_path: boot():/initramfs-linux-cachyos.img

/Arch Linux (CachyOS Fallback)
    protocol: linux
    path: boot():/vmlinuz-linux-cachyos
    cmdline: root=PARTUUID=08511545-f996-45c0-b58a-b9b49054e7c9 zswap.enabled=0 rw rootfstype=btrfs
    module_path: boot():/initramfs-linux-cachyos-fallback.img
