#!/bin/bash

export PATH="${PATH}:${HOME}/.local/bin/"

dir="$HOME/.config/rofi/launchers/type-1"
theme='style-1'

wallpapers=$HOME/Imagens/Wallpapers
image="$(ls $wallpapers | rofi -dmenu -i -p "  Selecionar wallpaper" -theme ${dir}/${theme}.rasi)"
wallpaper=$wallpapers/$image

if [[ -d $wallpapers/$image ]]; then
    echo "$wallpapers/$image é um diretório"
    wallpaper_temp="$image"
    sleep2
    wallpaper_location="$(ls $wallpapers/$image)"
elif [[ -f $wallpapers/$image ]]; then
    echo "$wallpapers/$image é um arquivo"
else
    echo "$wallpapers/$image não é válido"
    exit 1
fi

swww img $wallpaper --transition-type grow --transition-fps 75 --transition-duration 0.5 --transition-bezier 0.65,0,0.35,1 --transition-step 1

sleep 1.25

if [[ "$(<~/.cache/wal/mode )" = "dark" ]]; then
  wal -i $wallpaper --cols16
elif [[ "$(<~/.cache/wal/mode )" = "light" ]]; then
  wal -i $wallpaper -l --cols16
fi

pywalfox update

. $HOME/.config/mako/update-colors.sh
. $HOME/.config/spicetify/scripts/update-colors.sh
. $HOME/.config/cava/scripts/update-colors.sh